/**
 * Copyright (c) 2016 Duisburg-Essen University Library
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 **/

package org.mycore.ubo.importer;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.solr.client.solrj.SolrClient;
import org.apache.solr.client.solrj.SolrQuery;
import org.apache.solr.client.solrj.request.QueryRequest;
import org.apache.solr.client.solrj.response.QueryResponse;
import org.apache.solr.common.SolrDocumentList;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.filter.Filters;
import org.mycore.access.MCRAccessException;
import org.mycore.common.MCRConstants;
import org.mycore.common.MCRPersistenceException;
import org.mycore.common.MCRTransactionManager;
import org.mycore.common.config.MCRConfiguration2;
import org.mycore.common.content.MCRContent;
import org.mycore.common.content.MCRJDOMContent;
import org.mycore.common.content.transformer.MCRContentTransformer;
import org.mycore.common.content.transformer.MCRContentTransformerFactory;
import org.mycore.common.xml.MCRXMLFunctions;
import org.mycore.datamodel.metadata.MCRMetadataManager;
import org.mycore.datamodel.metadata.MCRObject;
import org.mycore.datamodel.metadata.MCRObjectID;
import org.mycore.frontend.MCRFrontendUtil;
import org.mycore.mods.enrichment.MCREnricher;
import org.mycore.solr.MCRSolrCoreManager;
import org.mycore.solr.MCRSolrUtils;
import org.mycore.solr.auth.MCRSolrAuthenticationLevel;
import org.mycore.solr.auth.MCRSolrAuthenticationManager;
import org.xml.sax.SAXException;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.TimeUnit;

import static org.mycore.common.MCRConstants.MODS_NAMESPACE;
import static org.mycore.common.MCRConstants.XPATH_FACTORY;

public abstract class ImportJob {

    private static final Logger LOGGER = LogManager.getLogger(ImportJob.class);

    private static final String PROJECT_ID = MCRConfiguration2.getString("UBO.projectid.default").get();

    private static final String ENRICHER_CONFIG_ID = "import-list";

    private List<Document> publications = new ArrayList<Document>();

    private ImportIdProvider importIdProvider = ((ImportIdProvider) MCRConfiguration2
        .instantiateClass(MCRConfiguration2.getStringOrThrow("UBO.Importer.ImportIdProvider.ListImport")));

    public String getID() {
        return importIdProvider.getImportId();
    }

    public List<Document> getPublications() {
        return publications;
    }

    public int getNumPublications() {
        return publications.size();
    }

    protected Optional<MCRContentTransformer> filterTransformer = null;

    public void transform(MCRContent source) throws IOException, JDOMException, SAXException {
        String transformerID = getTransformerID();
        MCRContentTransformer transformer = MCRContentTransformerFactory.getTransformer(transformerID);
        MCRContent converted = transformer.transform(source);

        Element collection = converted.asXML().getRootElement();
        for (Element publication : collection.getChildren()) {
            publications.add(new Document(publication.clone()));
        }
    }

    public void enrich(String configId){
        for (Document publication : publications) {
            MCREnricher enricher = new MCREnricher(configId);
            enricher.enrich(getContainedMODS(publication));
        }
    }

    public void enrich() {
        for (Document publication : publications) {
            MCREnricher enricher = new MCREnricher(ENRICHER_CONFIG_ID);
            enricher.enrich(getContainedMODS(publication));
        }
    }

    private Element getContainedMODS(Document publication) {
        Element mcrobject = publication.getRootElement();
        Element container = mcrobject.getChild("metadata").getChild("def.modsContainer").getChild("modsContainer");
        Element mods = container.getChild("mods", MCRConstants.MODS_NAMESPACE);
        return mods;
    }

    public void addFixedCategories(Element formInput) {
        CategoryAdder adder = new CategoryAdder(formInput);
        for (Document publication : publications) {
            adder.addCategories(publication);
            adder.setStatus(publication);
        }
    }

    /**
     * Sets a fixed genre to publications handled by this {@link ImportJob}. To make this work a <code>mods:genre</code>
     * must already be present in the publications handled by the ImportJob.
     *
     * @param parameters the form input as generated by import-list.xed
     *                   
     * @see org.mycore.ubo.importer.ImportJob#transform(Element)                   
     *
     * @return true if the genre was set, false otherwise
     */
    public boolean setFixedGenre(Element parameters) {
        Element ubogenre = parameters.getChild("ubogenre");
        if (ubogenre == null || ubogenre.getText().isEmpty()) {
            return false;
        }

        if (!MCRXMLFunctions.isCategoryID("ubogenre", ubogenre.getText())) {
            return false;
        }

        for (Document publication : publications) {
            Element genreElement = XPATH_FACTORY
                .compile("//mods:mods/mods:genre[@type='intern']", Filters.element(), null, MODS_NAMESPACE)
                .evaluateFirst(publication);

            // create new mods:genre element
            if (genreElement == null) {
                genreElement = new Element("genre", MODS_NAMESPACE);
                genreElement.setAttribute("type", "intern");
                genreElement.setAttribute("authorityURI", MCRFrontendUtil.getBaseURL() + "classifications/ubogenre");

                XPATH_FACTORY
                    .compile("//mods:mods", Filters.element(), null, MODS_NAMESPACE)
                    .evaluateFirst(publication)
                    .addContent(genreElement);
            }

            genreElement.setAttribute("valueURI",
                MCRFrontendUtil.getBaseURL() + "classifications/ubogenre#" + ubogenre.getText());
        }
        return true;
    }

    /**
     * Saves the publications of this {@link ImportJob} and adds the <code>importID</code> service flag.
     *
     * @return the list of objects saved in this method
     * */
    public List<MCRObject> savePublications() throws MCRPersistenceException, MCRAccessException {
        List<MCRObject> list = new ArrayList<>();
        for (Document publication : publications) {
            if (getFilterTransformer().isPresent()) {
                publication = applyFilterTransformer(publication, getFilterTransformer().get());
            }

            MCRObject obj = new MCRObject(publication);
            MCRObjectID oid = MCRMetadataManager.getMCRObjectIDGenerator().getNextFreeId(PROJECT_ID + "_mods");

            obj.setId(oid);
            obj.getService().addFlag("importID", this.getID());

            MCRMetadataManager.create(obj);
            list.add(obj);
        }
        return list;
    }

    protected Optional<MCRContentTransformer> getFilterTransformer() {
        if (filterTransformer == null) {
            Optional<String> name = MCRConfiguration2.getString(
                "MCR.ContentTransformer." + getTransformerID() + ".Filter");

            if (name.isEmpty()) {
                LOGGER.warn(
                    "Property 'MCR.ContentTransformer.{}.Filter' is not set. Set it to apply additional filtering before the publication is actually saved.",
                    getTransformerID());
                filterTransformer = Optional.empty();
            } else {
                filterTransformer = Optional.of(MCRContentTransformerFactory.getTransformer(name.get()));
            }
        }

        return filterTransformer;
    }

    private Document applyFilterTransformer(Document publication, MCRContentTransformer transformer) {
        try {
            return transformer.transform(new MCRJDOMContent(publication)).asXML();
        } catch (JDOMException | IOException e) {
            LOGGER.error(e.getMessage(), e);
            return publication;
        }
    }

    public void transform(Element formInput) throws Exception {
        LOGGER.info("Importing from " + getTransformerID() + "...");
        MCRContent source = getSource(formInput);
        transform(source);
        addFixedCategories(formInput);
        LOGGER.info("Transformed {} publications", getNumPublications());
    }

    public void saveAndIndex() throws MCRAccessException {
        savePublications();
        MCRTransactionManager.commitTransactions();
        tryToWaitUntilSolrIndexingFinished();
    }

    public String getQueryString() {
        return "importID:\"" + MCRSolrUtils.escapeSearchValue(this.getID()) + "\"";
    }

    private static final int MAX_SOLR_CHECKS = 10; // times

    private static final int SECONDS_TO_WAIT_BETWEEN_SOLR_CHECKS = 2;

    private void tryToWaitUntilSolrIndexingFinished() {
        SolrClient solrClient = MCRSolrCoreManager.getMainSolrClient();
        SolrQuery query = new SolrQuery();
        query.setQuery(getQueryString());
        query.setRows(0);

        try {
            int numTries = 0;
            long numFound;
            do {
                TimeUnit.SECONDS.sleep(SECONDS_TO_WAIT_BETWEEN_SOLR_CHECKS);
                QueryRequest queryRequest = new QueryRequest(query);
                MCRSolrAuthenticationManager.obtainInstance().applyAuthentication(queryRequest, MCRSolrAuthenticationLevel.SEARCH);
                QueryResponse response = queryRequest.process(solrClient);
                SolrDocumentList results = response.getResults();
                numFound = results.getNumFound();
                LOGGER.info("Check if SOLR indexed all publications: #" + numTries + " " + numFound + " / "
                    + getNumPublications());
            } while ((numFound < getNumPublications()) && (++numTries < MAX_SOLR_CHECKS));
        } catch (Exception ex) {
            LOGGER.warn(ex);
        }
    }

    /**
     * Allows to set another {@link ImportIdProvider}.
     *
     * @param newImportIdProvider the new {@link ImportIdProvider} to set.
     */
    protected void setImportIdProvider(ImportIdProvider newImportIdProvider) {
        this.importIdProvider = newImportIdProvider;
    }

    /**
     * Retrieve the current {@link ImportIdProvider}.
     *
     * @return the current {link ImportIdProvider}
     */
    protected ImportIdProvider getImportIdProvider() {
        return this.importIdProvider;
    }

    protected abstract String getTransformerID();

    protected abstract MCRContent getSource(Element formInput) throws Exception;
}
