# Register the metadata type "modsperson"
MCR.Metadata.Type.modsperson=true

# Event handler to collect and link person data in separate modsperson objects
MCR.EventHandler.MCRObject.022.Class=org.mycore.ubo.modsperson.MODSPersonLinkingEventHandler

# Event handler to process changes in modsperson objects
MCR.EventHandler.MCRObject.023.Class=org.mycore.ubo.modsperson.MODSPersonEventHandler

# Startup handler to initially fill the cache of all known person data
MCR.Startup.Class=%MCR.Startup.Class%, org.mycore.ubo.modsperson.MODSPersonCachingStartupHandler

# Extend SOLR indexing to also index modsperson objects with custom fields
MCR.URIResolver.xslImports.solr-document=%MCR.URIResolver.xslImports.solr-document%,modsperson-solr.xsl

# Extend display of metadata to modsperson object
MCR.URIResolver.xslIncludes.mycoreobject-extensions=mycoreobject-modsperson.xsl

MCR.MODS.Merger.alternativeName=org.mycore.mods.merger.MCRNameMerger

MCR.ContentTransformer.modsperson-json-normal.Class=org.mycore.common.content.transformer.MCRXsonifyTransformer
MCR.ContentTransformer.modsperson-json-normal.Schema=datamodel-mods.xsd
MCR.ContentTransformer.modsperson-json-normal.Settings.Class=org.mycore.common.content.transformer.MCRXsonifyTransformer$SettingsBuilder
MCR.ContentTransformer.modsperson-json-normal.Style.Class=org.mycore.common.content.transformer.MCRXsonifyTransformer$StyleBuilder
MCR.ContentTransformer.modsperson-json-normal.Style.TextKey=text

MCR.ContentTransformer.mycoreobject-modsperson-structure.Stylesheet=xsl/mycoreobject-modsperson-structure.xsl,xsl/html-layout.xsl,xsl/i18n-transformation-step.xsl,xsl/xhtml2html.xsl
MCR.ContentTransformer.mycoreobject-modsperson-structure.TransformerFactoryClass=org.apache.xalan.processor.TransformerFactoryImpl

# MyCoRe command line interface configuration
MCR.CLI.Classes.Internal=%MCR.CLI.Classes.Internal%,org.mycore.ubo.modsperson.migration.MODSPersonMigrationCommands

# custom pre-deletion action for deleting modsperson references in mods objects
MCR.PreDeleteAction.Class=org.mycore.ubo.modsperson.MODSPersonReferenceDeletionAction
